version: "2.4"

services:
    ignition:
        build:
            context: ./
        container_name: ignition
#        devices:
#            - "/dev/ttyUSB0:/dev/ttyUSB0"
        environment: 
            GATEWAY_ADMIN_PASSWORD: password
            IGNITION_EDITION: full
            GATEWAY_SYSTEM_NAME: home-automation-server
        image: ignition
        networks:
            network:
        ports:
            - "8088:8088"
        restart: always
        volumes:
            - ignition-data:/var/lib/ignition/data

networks:
    network:
        name: "camera-network"
    
volumes:
    ignition-data:
        name: ignition-data
